name: 'OneLib'
description: ''
author: Turtle
load: STARTUP
version: 1.0.0
api-version: 1.20
main: dev.turtle.onelib.Main
commands:
  onelib:
    aliases: [ol]
    description: none
permissions:
  onelib.admin:
    description: none